<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class productSeeders extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('products')->insert([
            //1
            ['nama'=>'fentanil',
            'description'=>'Hanya untuk nyeri berat dan harus diberikan oleh tim medis yang dapat melakukan resusitasi.',
            'form'=>"patch 25 mcg/jam",
            'restriction'=>"10 patch/bulan",
            'faskes1'=>"0",
            'faskes2'=>"1",
            'faskes3'=>"1",
            'category_id'=>"1"],
            ['nama'=>'hidromorfon',
            'description'=>'-',
            'form'=>"tab lepas lambat 16 mg ",
            'restriction'=>"30 tab/bulan",
            'faskes1'=>"0",
            'faskes2'=>"1",
            'faskes3'=>"1",
            'category_id'=>"1"],
            ['nama'=>'kodein',
            'description'=>'-',
            'form'=>"tab 20 mg",
            'restriction'=>"30 tab/bulan",
            'faskes1'=>"1",
            'faskes2'=>"1",
            'faskes3'=>"1",
            'category_id'=>"1"],
            //2
            ['nama'=>'asam mefenamat',
            'description'=>'-',
            'form'=>"tab 500 mg",
            'restriction'=>"30 tab/bulan",
            'faskes1'=>"1",
            'faskes2'=>"1",
            'faskes3'=>"1",
            'category_id'=>"2"],
            ['nama'=>'ibuprofen*',
            'description'=>'-',
            'form'=>"susp 200 mg/5 mL",
            'restriction'=>"1 btl/kasus",
            'faskes1'=>"1",
            'faskes2'=>"1",
            'faskes3'=>"1",
            'category_id'=>"2"],
            ['nama'=>'ketoprofen',
            'description'=>'Untuk nyeri sedang sampai berat pada pasien yang tidak dapat menggunakan analgesik secara oral',
            'form'=>"sup 100 mg",
            'restriction'=>"2 sup/hari, maks 3 hari",
            'faskes1'=>"0",
            'faskes2'=>"1",
            'faskes3'=>"1",
            'category_id'=>"2"],
            //3
            ['nama'=>'alopurinol',
            'description'=>'Tidak diberikan pada saat nyeri akut.',
            'form'=>"tab 300 mg",
            'restriction'=>"30 tab/bulan",
            'faskes1'=>"1",
            'faskes2'=>"1",
            'faskes3'=>"1",
            'category_id'=>"3"],
            ['nama'=>'kolkisin',
            'description'=>'-',
            'form'=>"tab 500 mcg",
            'restriction'=>"30 tab/bulan",
            'faskes1'=>"1",
            'faskes2'=>"1",
            'faskes3'=>"1",
            'category_id'=>"3"],
            ['nama'=>'probenesid',
            'description'=>'-',
            'form'=>"tab 500 mg",
            'restriction'=>"30 tab/bulan",
            'faskes1'=>"1",
            'faskes2'=>"1",
            'faskes3'=>"1",
            'category_id'=>"3"],
            //4
            ['nama'=>'amitriptilin',
            'description'=>'-',
            'form'=>"tab 25 mg",
            'restriction'=>"30 tab/bulan",
            'faskes1'=>"1",
            'faskes2'=>"1",
            'faskes3'=>"1",
            'category_id'=>"4"],
            ['nama'=>'gabapentin',
            'description'=>'Hanya untuk neuralgia pascaherpes atau nyeri neuropati diabetikum',
            'form'=>"kaps 300 mg",
            'restriction'=>"30 kaps/bulan",
            'faskes1'=>"0",
            'faskes2'=>"1",
            'faskes3'=>"1",
            'category_id'=>"4"],
            ['nama'=>'karbamazepin',
            'description'=>'Hanya untuk neuralgia trigeminal.',
            'form'=>"tab 100 mg",
            'restriction'=>"60 tab/bulan",
            'faskes1'=>"1",
            'faskes2'=>"1",
            'faskes3'=>"1",
            'category_id'=>"4"],
            //5
            ['nama'=>'bupivakain',
            'description'=>'Hanya untuk neuralgia trigeminal.',
            'form'=>"inj 0,5%",
            'restriction'=>"-",
            'faskes1'=>"0",
            'faskes2'=>"1",
            'faskes3'=>"1",
            'category_id'=>"5"],
            ['nama'=>'bupivakain heavy',
            'description'=>'Khusus untuk analgesia spinal.',
            'form'=>"inj 0,5% + glukosa 8%",
            'restriction'=>"-",
            'faskes1'=>"0",
            'faskes2'=>"1",
            'faskes3'=>"1",
            'category_id'=>"5"],
            ['nama'=>'etil klorida',
            'description'=>'-',
            'form'=>"spray 100 mL",
            'restriction'=>"-",
            'faskes1'=>"1",
            'faskes2'=>"1",
            'faskes3'=>"1",
            'category_id'=>"5"],
            //6
            ['nama'=>'deksmedetomidin',
            'description'=>'Untuk sedasi pada pasien di ICU, kraniotomi, bedah jantung dan operasi yang memerlukan waktu pembedahan yang lama.',
            'form'=>"inj 100 mcg/mL",
            'restriction'=>"-",
            'faskes1'=>"0",
            'faskes2'=>"1",
            'faskes3'=>"1",
            'category_id'=>"6"],
            ['nama'=>'desfluran',
            'description'=>'-',
            'form'=>"ih",
            'restriction'=>"-",
            'faskes1'=>"0",
            'faskes2'=>"1",
            'faskes3'=>"1",
            'category_id'=>"6"],
            ['nama'=>'halotan',
            'description'=>'Tidak boleh digunakan berulang dan Tidak untuk pasien dengan gangguan fungsi hati.',
            'form'=>"ih",
            'restriction'=>"-",
            'faskes1'=>"0",
            'faskes2'=>"1",
            'faskes3'=>"1",
            'category_id'=>"6"],
            //7
            ['nama'=>'atropin',
            'description'=>'-',
            'form'=>"inj 0,25 mg/mL (i.v./s.k.)",
            'restriction'=>"-",
            'faskes1'=>"1",
            'faskes2'=>"1",
            'faskes3'=>"1",
            'category_id'=>"7"],
            ['nama'=>'diazepam',
            'description'=>'-',
            'form'=>"inj 5 mg/mL",
            'restriction'=>"-",
            'faskes1'=>"1",
            'faskes2'=>"1",
            'faskes3'=>"1",
            'category_id'=>"7"],
            ['nama'=>'midazolam',
            'description'=>'Dapat digunakan untuk premedikasi sebelum induksi anestesi dan rumatan selama anestesi umum.',
            'form'=>"inj 1 mg/mL (i.v.)",
            'restriction'=>"- Dosis rumatan:
                1 mg/jam (24
                mg/hari).
                - Dosis premedikasi:
                8 vial/kasus.",
            'faskes1'=>"0",
            'faskes2'=>"1",
            'faskes3'=>"1",
            'category_id'=>"7"],
            //8
            ['nama'=>'deksametason',
            'description'=>'-',
            'form'=>"inj 5 mg/mL",
            'restriction'=>"20 mg/hari.",
            'faskes1'=>"1",
            'faskes2'=>"1",
            'faskes3'=>"1",
            'category_id'=>"8"],
            ['nama'=>'difenhidramin',
            'description'=>'-',
            'form'=>"inj 10 mg/mL (i.v./i.m.)",
            'restriction'=>"30 mg/hari.",
            'faskes1'=>"1",
            'faskes2'=>"1",
            'faskes3'=>"1",
            'category_id'=>"8"],
            ['nama'=>'epinefrin (adrenalin)',
            'description'=>'-',
            'form'=>"inj 1 mg/mL",
            'restriction'=>"-",
            'faskes1'=>"1",
            'faskes2'=>"1",
            'faskes3'=>"1",
            'category_id'=>"8"],
            //9
            ['nama'=>'atropin',
            'description'=>'-',
            'form'=>"inj 0,25 mg/mL (i.v.)",
            'restriction'=>"-",
            'faskes1'=>"1",
            'faskes2'=>"1",
            'faskes3'=>"1",
            'category_id'=>"9"],
            ['nama'=>'efedrin',
            'description'=>'-',
            'form'=>"inj 50 mg/mL",
            'restriction'=>"-",
            'faskes1'=>"0",
            'faskes2'=>"1",
            'faskes3'=>"1",
            'category_id'=>"9"],
            ['nama'=>'kalsium glukonat',
            'description'=>'-',
            'form'=>"inj 10%",
            'restriction'=>"-",
            'faskes1'=>"1",
            'faskes2'=>"1",
            'faskes3'=>"1",
            'category_id'=>"9"],
            //10
            ['nama'=>'magnesium sulfat',
            'description'=>'-',
            'form'=>"serb",
            'restriction'=>"-",
            'faskes1'=>"1",
            'faskes2'=>"1",
            'faskes3'=>"1",
            'category_id'=>"10"]
        ]);
    }
}
